language: android
jdk: oraclejdk8

before_install:
- yes | sdkmanager "platforms;android-28"

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-23
    - android-24
    - android-26

env:
- GRADLE_OPTS="-Xmx512m -XX:MaxPermSize=512m"

script:
 - ./gradlew check